// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rumlwvzmakfplcwegtwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1bWx3dnptYWtmcGxjd2VndHd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NDkyMjYsImV4cCI6MjA3MDQyNTIyNn0.LtFENWF_5bxfBnmupMepLiVg7bgic_xH-0uBtMyMYDo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});